"""
Authentication endpoints powered by FastAPI Users.

This module provides production-ready authentication with minimal code:
- User registration
- Login/logout with JWT
- Password reset
- Email verification
- Profile management

All endpoints are auto-generated by FastAPI Users with proper:
- Validation
- Error handling
- Security best practices
- OpenAPI documentation

Best Practices:
    - Minimal custom code (FastAPI Users handles complexity)
    - Industry-standard endpoints
    - Proper HTTP status codes
    - Clear error messages
    - Type-safe with Pydantic
"""

import structlog
from fastapi import APIRouter

from app.core.config import settings
from app.core.fastapi_users_instance import auth_backend, fastapi_users
from app.schemas.user_fastapi import UserCreate, UserRead, UserUpdate

logger = structlog.get_logger(__name__)

router = APIRouter()

# ==============================================================================
# FastAPI Users Auto-Generated Routers
# ==============================================================================
# These routers provide production-ready authentication endpoints with:
# - Proper validation
# - Security best practices
# - Error handling
# - OpenAPI documentation
# ==============================================================================

# Auth Router - JWT Login/Logout
# Endpoints:
#   POST /auth/jwt/login  - Login with email/password, returns JWT
#   POST /auth/jwt/logout - Logout (invalidates token)
router.include_router(
    fastapi_users.get_auth_router(auth_backend),
    prefix="/jwt",
    tags=["auth"],
)
logger.info("✅ Registered JWT auth router: /auth/jwt/login, /auth/jwt/logout")

if settings.AUTH_ENABLE_REGISTRATION:
    # Register Router
    # Endpoints:
    #   POST /auth/register - Register new user
    router.include_router(
        fastapi_users.get_register_router(UserRead, UserCreate),
        tags=["auth"],
    )
    logger.info("✅ Registered register router: /auth/register (public registration enabled)")
else:
    logger.info("⚠️ Public registration disabled (AUTH_ENABLE_REGISTRATION=false)")

# Users Router - Profile Management
# Endpoints:
#   GET    /auth/me       - Get current user profile
#   PATCH  /auth/me       - Update current user profile
#   DELETE /auth/me       - Delete current user account
router.include_router(
    fastapi_users.get_users_router(UserRead, UserUpdate),
    prefix="",
    tags=["auth"],
)
logger.info("✅ Registered users router: /auth/me")

if settings.AUTH_ENABLE_PASSWORD_RESET:
    # Password Reset Router
    # Endpoints:
    #   POST /auth/forgot-password - Request password reset
    #   POST /auth/reset-password  - Reset password with token
    router.include_router(
        fastapi_users.get_reset_password_router(),
        tags=["auth"],
    )
    logger.info("✅ Registered password reset router (public reset enabled)")
else:
    logger.info("⚠️ Public password reset disabled (AUTH_ENABLE_PASSWORD_RESET=false)")

if settings.AUTH_ENABLE_EMAIL_VERIFICATION:
    # Verification Router
    # Endpoints:
    #   POST /auth/request-verify-token - Request email verification token
    #   POST /auth/verify               - Verify email with token
    router.include_router(
        fastapi_users.get_verify_router(UserRead),
        tags=["auth"],
    )
    logger.info("✅ Registered email verification router (public verification enabled)")
else:
    logger.info("⚠️ Email verification endpoints disabled (AUTH_ENABLE_EMAIL_VERIFICATION=false)")

# ==============================================================================
# Summary of Available Endpoints
# ==============================================================================
# Authentication:
#   POST /auth/jwt/login            - Login (email + password → JWT)
#   POST /auth/jwt/logout           - Logout
#
# Registration:
#   POST /auth/register             - Register new user
#
# Profile:
#   GET  /auth/me                   - Get current user
#   PATCH /auth/me                  - Update profile
#   DELETE /auth/me                 - Delete account
#
# Password Management:
#   POST /auth/forgot-password      - Request reset
#   POST /auth/reset-password       - Reset with token
#
# Email Verification:
#   POST /auth/request-verify-token - Request verification
#   POST /auth/verify               - Verify email
# ==============================================================================
