"""add_location_contacts

Revision ID: 0147eedda887
Revises: 20251230_add_organizations
Create Date: 2026-01-17 00:18:55.667620

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0147eedda887"
down_revision = "20251230_add_organizations"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_contacts",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id", "organization_id"],
            ["locations.id", "locations.organization_id"],
            name="fk_location_contacts_location_org",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_location_contacts_id"),
        "location_contacts",
        ["id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_location_contacts_location_id"),
        "location_contacts",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        "ix_location_contacts_org_location",
        "location_contacts",
        ["organization_id", "location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_location_contacts_organization_id"),
        "location_contacts",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_location_contacts_organization_id"), table_name="location_contacts")
    op.drop_index("ix_location_contacts_org_location", table_name="location_contacts")
    op.drop_index(op.f("ix_location_contacts_location_id"), table_name="location_contacts")
    op.drop_index(op.f("ix_location_contacts_id"), table_name="location_contacts")
    op.drop_table("location_contacts")
    # ### end Alembic commands ###
